#!/usr/bin/env bash

versions () {
	if [ -x "$(command -v git)" ]; then
		echo $(git config user.name)
		echo $(git config user.email)
		echo ""
		echo $(git --version)
	else
		echo "git:   NOT INSTALLED"
	fi

	if [ -x "$(command -v node)" ]; then
		echo "node: $(node -v)"
	else
		echo "node: NOT INSTALLED"
	fi

	if [ -x "$(command -v npm)" ]; then
		echo "npm: $(npm -v)"
	else
		echo "npm: NOT INSTALLED"
	fi

	if [ -x "$(command -v ruby)" ]; then
		echo "$(ruby -v)"
	else
		echo "ruby: NOT INSTALLED"
	fi

	if [ -x "$(command -v bower)" ]; then
		echo "$(bower -v)"
	else
		echo "bower: NOT INSTALLED"
	fi
}