#!/usr/bin/env bash
source "$(dirname "$0")"/../_script/logging

cd "$(dirname "$0")"/..

header "Main Dependency Check"
deps=$(cat ./dependencies)

for dep in $deps
do
	check_for_dep "$dep"
done

echo ''
