#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname "$0")"/..

# find the installers and run them iteratively
find . -maxdepth 2 -name install.sh | egrep -v "_build" | sort -n | while read installer
do 
  sh -c "${installer}"
done
