#!/usr/bin/env bash
source ~/.dotfiles/script/logging

cd "$(dirname $0)"/..

dep_files=$(find . -name dependencies_apt)
for dep_list in $dep_files
do
	header "$(get_dir $dep_list) Dependencies"
	for dep in $(cat $dep_list)
	do
		check_or_install_dep $dep
	done
done

footer "Dependencies Installed!"