#!/usr/bin/env bash

# Create useful gitignore files
# Usage: gi [param]
# param is a comma separated list of ignore profiles.
# If param is ommited choose interactively.

function __gi() {
  curl -L -s https://www.gitignore.io/api/"$@"
}

if  [ "$#" -eq 0 ]; then
  IFS+=","
  for item in $(__gi list); do
    echo $item
  done | fzf --multi --ansi | paste -s -d "," - |
  { read result && __gi "$result" > .gitignore; }
else
  __gi "$@" > .gitignore
fi
