#!/usr/bin/env bash

# Create useful gitignore files
# Usage: gi [param]
# param is a comma separated list of ignore profiles.
# If param is ommited choose interactively.

function __gi() {
  curl -L -s https://www.gitignore.io/api/"$*"
}

if  [ "$#" -eq 0 ]; then
  IFS+=","
  for item in $(__gi list); do
    echo $item
  done | fzf --multi --ansi --bind 'ctrl-l:cancel' | paste -s -d "," - |
  { read result && __gi "$result" > .gitignore; }
elif [ "$1" = "node" ]; then
  __gi macos,visualstudiocode,node,windows > .gitignore
else
  __gi "$@" > .gitignore
fi

if [ $? -eq 0 ]; then
  echo "Created .gitignore"
fi
