#!/usr/bin/env bash
#
# Generate new README.md

if [ -f ./README.md ]; then echo "README.md already exists"; exit 0; fi

sed "s/Project Name/$(basename "$PWD")/g" "$DOTFILES/git/README.template" > README.md
echo "README.md file generated."
