name: Dotfiles Install

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-14
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.6.0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.1
          run_install: false

      - name: Build phoenix
        run: |
          pnpm -C phoenix install
          pnpm -C phoenix run typecheck
          pnpm -C phoenix run build

      - name: Install dotfiles
        run: ./install --except asdf

